services:
  scripts:
    image: npcdw/scripts:latest
    container_name: scripts
    volumes:
      - "${PWD}/config/:/scripts/config"
    environment:
      TZ : 'Asia/Shanghai'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'